### ISSUE TITLE
Authenticated requests failing with "requires authentication" error message

### ISSUE THREAD

**Issue by kfcampbell** [octokit/source-generator#16]
Upon generating and running the sample application (with a `GITHUB_TOKEN` exported, the code block

```go
userEmails, err := client.User().Emails().Get(context.Background(), nil)
if err != nil {
	log.Fatalf("%v\n", err)
}
```

throws an error. This is printed as `error status code received from the API` but when debugging, the error contains a message that says "Requires authentication". 

We need to discover what about the sample app isn't setting up our credentials correctly and fix it.

**Comment by baywet** [comment]
This might be caused by the host validation aspect of the authentication layers, if you share more about how you've implemented the authentication and how you are currently using it, I could try to help with that aspect.
You should have a look at the [github todo demo](https://github.com/baywet/GitHubTodoDemo) I put together in multiple languages.
In my case I'm doing device code flow, but you should be able to adapt to any flow at this point.

**Comment by kfcampbell** [comment]
This was my own fault for not setting the authentication correctly (I forgot the "Bearer" piece)! It can be closed now.
